import { apiSlice } from './apiSlice.js';

export const adminServiceApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // --- DASHBOARD STATS ---
    getDashboardStats: builder.query({
      query: () => '/admin/dashboard',
      keepUnusedDataFor: 60, // Cache data selama 60 detik agar tidak spam request
    }),

    getProducts: builder.query({
      query: (params) => ({
        url: '/products',
        params: params, // Ini untuk menangani categoryId filter
      }),
      providesTags: ['Products'],
    }),
    getAdminProducts: builder.query({
      query: () => '/products',
      providesTags: ['Products'],
    }),
    getProductById: builder.query({
      query: (id) => `/products/${id}`,
      providesTags: (result, error, id) => [{ type: 'Products', id }],
    }),
    createProduct: builder.mutation({
      query: (formData) => ({
        url: '/products',
        method: 'POST',
        body: formData, // FormData otomatis menangani boundary multipart
      }),
      invalidatesTags: ['Products'],
    }),
    updateProduct: builder.mutation({
      query: ({ id, formData }) => ({
        url: `/products/${id}`,
        method: 'PATCH',
        body: formData,
      }),
      invalidatesTags: (result, error, { id }) => ['Products', { type: 'Products', id }],
    }),
    deleteProduct: builder.mutation({
      query: (id) => ({
        url: `/products/${id}`,
        method: 'DELETE',
      }),
      invalidatesTags: ['Products'],
    }),
  }),
});

// Export hooks generated by RTK Query (Updated)
export const { 
  useGetDashboardStatsQuery,
  useGetAdminProductsQuery,
  useGetProductsQuery,
  useGetProductByIdQuery,
  useCreateProductMutation, 
  useUpdateProductMutation, 
  useDeleteProductMutation 
} = adminServiceApi;

export const useGetAdminProductByIdQuery = useGetProductByIdQuery;